# version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./.qdrant_data:/qdrant/storage
    restart: unless-stopped


  vllm_embed:
    image: vllm/vllm-openai:latest
    container_name: vllm_embed
    ports:
      - "8081:8000"
    volumes:
      - ./.hf_cache/BAAI/bge-m3:/root/.cache/huggingface
    command: >
      BAAI/bge-m3
      --served-model-name qwen3-embed
      --max-model-len 8192
      --max-num-batched-tokens 8192
      --max-num-seqs 64
      --gpu-memory-utilization 0.15
      --trust-remote-code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    ports:
      - "8000:8000"
    volumes:
      - ./.hf_cache:/root/.cache/huggingface
    command: >
      Qwen/Qwen3-8B-AWQ
      --quantization awq_marlin
      --enforce-eager
      --gpu-memory-utilization 0.65
      --max-model-len 8192
      --max-num-batched-tokens 8192
      --max-num-seqs 32
      --served-model-name qwen3-4b
      --trust-remote-code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # restart: unless-stopped


  tei-rerank:
    image: ghcr.io/huggingface/text-embeddings-inference:cuda-latest
    container_name: tei-rerank
    ports:
      - "8082:80"
    volumes:
      - ./.hf_cache/tei/rerank:/data
    command: >
      --model-id BAAI/bge-reranker-v2-m3
      --max-batch-tokens 8192
      --max-client-batch-size 32
      --auto-truncate
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    restart: unless-stopped


  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    network_mode: host
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: uvicorn api.server:app --host 0.0.0.0 --port 10000
    depends_on:
      - qdrant
      - vllm
      - vllm_embed
      - tei-rerank
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bot
    network_mode: host
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: python -u api/bot.py
    depends_on:
      - api
    restart: unless-stopped


# для запуска на cpu
          # tei:
  #   image: ghcr.io/huggingface/text-embeddings-inference:cpu-ipex-latest
  #   container_name: tei
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./.hf_cache/tei/embedding:/data
  #   # environment:
  #     # - OMP_NUM_THREADS=16
  #     # - MKL_NUM_THREADS=16
  #     # - KMP_AFFINITY=granularity=fine,compact,1,0
  #   command: >
  #     --model-id BAAI/bge-m3
  #     --dtype bfloat16
  #     --max-batch-tokens 8192
  #     --max-client-batch-size 32
  #     --auto-truncate
  #   # cpuset: "0-15"
  #   restart: unless-stopped