services:
  vllm_embed:
    image: vllm/vllm-openai:latest
    container_name: vllm_embed
    ports:
      - "8081:8000"
    volumes:
      - ./.hf_cache/harrier_0.6b:/root/.cache/huggingface
    command: >
      codefuse-ai/F2LLM-v2-0.6B
      --served-model-name harr-embed
      --max-model-len 512
      --max-num-batched-tokens 8192
      --max-num-seqs 64
      --gpu-memory-utilization 0.4
      --trust-remote-code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]