services:
  vllm14b:
    image: vllm/vllm-openai:latest
    container_name: vllm14b
    ports:
      - "8083:8000"
    volumes:
  # Локальная папка для всех весов моделей HuggingFace
      - ./.hf_cache/eval:/root/.cache/huggingface
    environment:
      - VLLM_USE_V1=0               
      - VLLM_ATTENTION_BACKEND=TRITON
      # - VLLM_ENGINE_VERSION=v0
      # - VLLM_ATTN_BACKEND=TRITON_ATTN
    command:                                     
      froogai/Qwen3-14B-AWQ
      --quantization awq_marlin
      --enforce-eager
      --gpu-memory-utilization 0.8
      --max-model-len 8192
      --max-num-batched-tokens 8192
      --max-num-seqs 32
      --served-model-name qwen3-14b
      --trust-remote-code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # restart: unless-stopped
    # shm_size: 8gb