services:
  vllm_embed:
    image: vllm/vllm-openai:latest
    container_name: vllm_embed
    ports:
      - "8081:8000"
    volumes:
      - ./.hf_cache/BAAI/bge-m3:/root/.cache/huggingface
    command: >
      BAAI/bge-m3
      --served-model-name qwen3-embed
      --max-model-len 8192
      --max-num-batched-tokens 8192
      --max-num-seqs 64
      --gpu-memory-utilization 0.3
      --trust-remote-code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]