services:

  # tei:
  #   image: ghcr.io/huggingface/text-embeddings-inference:latest
  #   command: --model-id deepvk/USER-base --port 8080
  #   ports:
  #     - "8081:8080"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-ipex-latest
    container_name: tei
    ports:
      - "8081:80"
    volumes:
      - ./.hf_cache/tei/deepvk/USER-base:/data
    environment:
      - OMP_NUM_THREADS=16
      - MKL_NUM_THREADS=16
      - KMP_AFFINITY=granularity=fine,compact,1,0
    command: >
      --model-id deepvk/USER-base
      --dtype bfloat16
      --max-batch-tokens 8192
      --max-client-batch-size 64
      --auto-truncate
    cpuset: "0-15"
    restart: unless-stopped